from typing import Dict, Any
from pathlib import Path
import subprocess

from orchestrator.agents.base import Agent
from orchestrator.ctb import CTB
from orchestrator.guard import ensure_guarded_write
from orchestrator.db import create_artifact

class DevOpsAgent(Agent):
    """DevOps Agent: Manages infrastructure, CI/CD, and tooling scripts."""
    ROLE = "DevOps"

    def __init__(self, llm):
        super().__init__(llm)

    async def run(self, ctb: CTB) -> Dict[str, Any]:
        self._log(ctb, "INFO", f"Starting objective: {ctb.objective}")

        target_file_path = ""
        if "docker-compose" in ctb.objective.lower():
            target_file_path = "docker-compose.yml"
        elif "tooling scripts" in ctb.objective.lower():
            target_file_path = "tools/run_tests.sh"
        
        if not target_file_path:
            msg = "Could not determine target file from task objective."
            self._log(ctb, "ERROR", msg)
            return {"status": "Failed", "error": msg}

        try:
            with open(f"agent_framework/orchestrator/prompts/{self.ROLE.lower()}.system.txt", "r") as f:
                system_prompt = f.read()
        except FileNotFoundError:
            system_prompt = "You are the DevOps Agent. Your goal is to provision infrastructure."

        user_prompt = (
            f"Generate the content for the file '{target_file_path}'.\n"
            f"Objective: {ctb.objective}\n"
            f"Constraints: {ctb.constraints}. IMPORTANT: Do not hardcode secrets; use environment variables or env_file.\n"
            f"Acceptance Criteria: {ctb.acceptance}\n\n"
            f"ATTACHMENTS:\n---\nAGENTS.MD:\n{ctb.attachments.get('AGENTS.MD', 'N/A')}\n---\n"
            f"BACKLOG.MD:\n{ctb.attachments.get('BACKLOG.md', 'N/A')}\n---\n"
        )

        self._log(ctb, "INFO", f"Calling LLM to generate content for '{target_file_path}'.")
        file_content = await self.llm.complete(
            role=self.ROLE,
            system_prompt=system_prompt,
            user_prompt=user_prompt,
            task_id=ctb.task_id,
            story_id=ctb.story_id
        )

        try:
            guarded_path = ensure_guarded_write(
                guard_patterns=ctb.guard_paths, root=".", write_path=target_file_path
            )
            
            Path(guarded_path).parent.mkdir(parents=True, exist_ok=True)
            Path(guarded_path).write_text(f"# Generated by {self.ROLE} Agent for task {ctb.task_id}\n\n" + file_content)
            
            self._log(ctb, "INFO", f"Successfully wrote artifact.", meta={"path": str(guarded_path)})

            # Chạy linting, type checking và tests theo plan.md
            self._log(ctb, "INFO", "Running quality checks (lint, type-check, tests)...")
            checks = [
                ("Lint", ["bash", "agent_framework/tools/run_lint.sh"]),
                ("Typecheck", ["bash", "agent_framework/tools/run_typecheck.sh"]),
                ("Tests", ["bash", "agent_framework/tools/run_tests.sh"])
            ]

            for label, command in checks:
                result = subprocess.run(command, capture_output=True, text=True)
                if result.returncode != 0:
                    # Một số script có thể bỏ qua (vd: không có runner)
                    stdout = result.stdout or ""
                    stderr = result.stderr or ""
                    if label == "Tests" and "No test runner configured" in stdout:
                        self._log(ctb, "WARN", "Tests skipped: No test runner configured.", meta={"stdout": stdout[-1000:], "stderr": stderr[-1000:]})
                        continue
                    self._log(ctb, "ERROR", f"{label} script failed.", meta={"stdout": stdout[-1000:], "stderr": stderr[-1000:]})
                    return {"status": "Failed", "error": f"{label} check failed"}
                else:
                    self._log(ctb, "INFO", f"{label} check passed.", meta={"stdout": (result.stdout or "")[-1000:]})

            create_artifact(ctb.story_id, ctb.task_id, str(guarded_path), "code")
            self._log(ctb, "INFO", "All quality checks passed and artifact registered.")

            return {"status": "Coding Complete", "artifacts": [str(guarded_path)]}
        except PermissionError as e:
            self._log(ctb, "ERROR", f"File write permission error: {e}")
            return {"status": "Failed", "error": str(e)}
