default_provider: "openai"

# Khai báo thông tin cho từng provider. Mỗi provider cần set API key tương ứng trong môi trường.
# Ví dụ:
#   export OPENAI_API_KEY="sk-..."
#   export ANTHROPIC_API_KEY="sk-ant-..."
#   export GOOGLE_API_KEY="AIza..."
providers:
  openai:
    api_key_env: "OPENAI_API_KEY"
    base_url: "https://api.openai.com/v1"
    organization_env: "OPENAI_ORG_ID"   # tuỳ chọn, bỏ trống nếu không dùng

  anthropic:
    api_key_env: "ANTHROPIC_API_KEY"
    base_url: "https://api.anthropic.com"

  google:
    api_key_env: "GOOGLE_API_KEY"
    base_url: "https://generativelanguage.googleapis.com/v1beta"

  perplexity:
    api_key_env: "PERPLEXITY_API_KEY"
    base_url: "https://api.perplexity.ai"

# Định nghĩa model mặc định cho từng vai trò. Có thể pha trộn nhiều provider khác nhau.
models:
  PM:
    provider: "google"
    name: "gemini-2.5-pro"
    temperature: 0.2
    max_tokens: 65536

  DevOps:
    provider: "openai"
    name: "gemini-2.5-flash"
    temperature: 0.2
    max_tokens: 1600

  BE:
    provider: "openai"
    name: "gemini-2.5-flash"
    temperature: 0.2
    max_tokens: 65536

  FE:
    provider: "google"
    name: "gemini-2.5-flash"
    temperature: 0.3
    max_tokens: 65536

  ML:
    provider: "google"
    name: "gemini-2.5-flash"
    temperature: 0.1
    max_tokens: 65536

  QA:
    provider: "google"
    name: "gemini-2.5-flash"
    temperature: 0.1
    max_tokens: 65536

# Overrides cho phép ép provider/model riêng theo story hoặc task quan trọng.
# Ví dụ dưới đây minh hoạ cách force model mạnh hơn cho task A1.T03 và story B2.
overrides:
  tasks:
    "A1.T03":
      provider: "google"
      name: "gemini-2.5-flash"
      temperature: 0.1
      max_tokens: 2200
  stories:
    "B2":
      provider: "google"
      name: "gemini-2.5-flash"
      temperature: 0.15
      max_tokens: 2500
